name: flappy_bird
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flame: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flame_audio: ^2.1.2
flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/audio/

  fonts:
    - family: Game
      fonts:
        - asset: assets/fonts/Game.ttf
